services:

  db_postgres:
    image: postgres:13.5
    container_name: db_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - app_network

  pgadmin_postgres:
    image: dpage/pgadmin4
    container_name: pgadmin_postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: "jps.tentis@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "pass"
    ports:
      - "5050:80"
    depends_on:
      - db_postgres
    networks:
      - app_network

volumes:
  postgres:

networks:
  app_network:
    driver: bridge